version: '2.1'

services:
  docker-ts-debug:
    container_name: docker-ts-debug
    restart: always
    env_file: 
      - .env
    # environment: 
    #   NODE_ENV: ${NODE_ENV}
    #   NODE_SERVER_PORT: ${NODE_SERVER_PORT}
    #   #MONGO
    #   MONGODB_DB_HOST_PORT_LIST: mongodb:27017
    #   MONGODB_DB_NAME: ${MONGODB_DB_NAME}

    build: . # if build arg not present, it will try to pull from registry
    image: docker-ts-debug:dev
    entrypoint: ["npm", "run", "debug"]
    volumes: 
      - ./dist:/server/dist
    ports:
      - ${DOCKER_TS_DEBUG_NODE_PORT}:${DOCKER_TS_DEBUG_NODE_PORT}
      - 9225:9225
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6
    container_name: mongo
    volumes: 
      - .mongo/data:/data
    ports: 
      - 27018:27017

