version: '2.1'

services:
  cdt_box:
    container_name: cdt_box
    restart: always
    env_file: #not needed as docker compose looks for .env by default
      - .env
    build: . # if build arg not present, it will try to pull from registry
    image: cdt_box:local
    command: ["debug"]
    volumes: 
      - ./dist:/server/dist
    ports:
      - 4000:4000
      - 9229:9229
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6
    container_name: mongo
    volumes: 
      - ./data/db:/data/db
    ports: 
      - 27018:27017

