version: '2.1'

services:
  docker-ts-debug:
    container_name: docker-ts-debug
    restart: always
    env_file: 
      - .env
    environment: # Another way to define env vars
      NODE_ENV: docker
      MONGODB_HOST_AND_PORT_LIST: mongodb:27017

    build: # if build arg not present, it will try to pull from registry
      context: . 
      # args: 
      #   - GIT_COMMIT: "git log -1 --pretty=format:%H"
    image: docker-ts-debug:dev
    entrypoint: ["npm", "run", "debug"]
    volumes: 
      - ./dist:/server/dist
    ports:
      - ${DOCKER_TS_DEBUG_NODE_PORT}:${DOCKER_TS_DEBUG_NODE_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6
    container_name: mongo
    volumes: 
      - .mongo/data:/data
    ports: 
      - 27018:27017

